# @package trainer
_target_: pytorch_lightning.Trainer

gpus: 0

min_epochs: 1
max_epochs: 2

# prints
progress_bar_refresh_rate: null
weights_summary: null
profiler: null

# debugs
num_sanity_val_steps: 0
fast_dev_run: True
overfit_batches: 0
track_grad_norm: -1
terminate_on_nan: False