repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10240"]
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args: []
        files: .
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: []
        files: .
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: []
        files: .
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: local
    hooks:
      - id: clean
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit-config update"
