# @package scraper
_target_: reddit_post_classification.utils.Scraper

client_id:
client_secret:
user_agent:

subreddit_names: ${subreddit_names}
sort: new
limit: 1000
selftext_only: True
fname: ${data_dir}/raw/reddit_posts.csv
since: null