# @package scraper
_target_: reddit_post_classification.Scraper

client_id: null
client_secret: null
user_agent: null

subreddit_names: ${subreddit_names}
sort: new
limit: 1000
selftext_only: True
fname: ${data_dir}/raw/reddit_posts.csv
since: null