# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python scripts/train.py -m model=RNN hparams_search=rnn_optuna hydra.sweeper.n_trials=30

defaults:
  - override /hydra/sweeper: optuna

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # number of experiments that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      optimizer.lr:
        type: float
        low: 0.0001
        high: 0.01
      model.embedding_dim:
        type: categorical
        choices: [64, 128, 256]
      model.rnn_type:
        type: categorical
        choices: [GRU, LSTM]
      model.rnn_hidden_dim:
        type: categorical
        choices: [64, 128, 256]
      model.rnn_dropout:
        type: float
        low: 0.1
        high: 0.5
        step: 0.1
      model.rnn_num_layers:
        type: int
        low: 2
        high: 5