# @package model
_target_: reddit_post_classification.models.RNN
embedding_dim: 128
rnn_type: GRU
rnn_hidden_dim: 128
rnn_dropout: 0.3
rnn_num_layers: 2
bidirectional: true
num_labels: ???
vocab_size: ???
padding_idx: ???