# @package callbacks
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${monitor}
  save_top_k: 1
  save_last: False
  save_weights_only: True
  mode: "max"
  verbose: False
  dirpath: "checkpoints/"
  filename: "lit_model"

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${monitor}
  patience: 5
  mode: "max"
  min_delta: 0