# @package datamodule
_target_: reddit_post_classification.data.RedditDataModule
data_dir: ${data_dir}
labels: ${subreddit_names}
batch_size: 32
num_workers: 0
pin_memory: false
max_seq_len: 512
val_size: 0.1
test_size: 0.1