name: Deployment

on:
  push:
    branches: [master]
    paths:
      - "artifacts/**"
      - "backend/**"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build Docker image
        run: docker build --tag reddit-post-classifier --file backend/Dockerfile .
      - name: Push image to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: reddit-post-classifier:latest
      - name: Update lambda with image
        run: aws lambda update-function-code --function-name predict-reddit-post --image-uri 250854891162.dkr.ecr.us-east-1.amazonaws.com/reddit-post-classifier:latest
