name: testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture: x64

      - name: Install dependencies
        run: python -m pip install pytest==6.1.1 scikit-learn==0.24.2

      - name: Execute tests
        run: pytest backend
